# Generated by Django 4.1.7 on 2023-02-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300, unique=True, verbose_name='File name')),
                ('path', models.FileField(max_length=300, upload_to='csv/', verbose_name='Path')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
        ),
    ]
