# Generated by Django 4.1.6 on 2023-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcsv',
            name='path',
            field=models.FileField(max_length=300, upload_to='csv/', verbose_name='Path'),
        ),
    ]
