# Generated by Django 4.1.6 on 2023-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0003_alter_datasetcsv_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcsv',
            name='filename',
            field=models.CharField(blank=True, max_length=300, verbose_name='File name'),
        ),
    ]
