# Generated by Django 4.1.6 on 2023-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsApp', '0004_datasetcsv_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcsv',
            name='filename',
            field=models.CharField(max_length=300, unique=True, verbose_name='File name'),
        ),
    ]
